version: '3.7'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DATABASE_URL: postgres://user:password@database:5432/mydatabase
    depends_on:
      - database
    ports:
      - "3000:3000" # Exponer el puerto 3000
volumes:
  pgdata: